fix(transport): merge internal/dca into cert package
googleapis/google-api-go-client pull request #1040
Opened 2021-05-25 22:34 UTC by shinfan

- Merge the two packages since both packages handle client certificate discovery
- Create ShouldUseMTLSEndpoint(...) which returns if the MTLS endpoint should be used. This method is needed for Terraform to onboard mTLS and we do not want to Terraform to write its own logic to detect which endpoint to use.

2021-05-26 21:21 UTC, codyoss requested changes

2021-05-26 21:21 UTC, codyoss commented on transport/cert/dca.go
> +func GetClientCertificateSourceAndEndpoint(settings *internal.DialSettings) (Source, string, error) {
I don't think this package can be made public as is. The input to this function is a struct that can't be made public. I think for now a little bit of copying is the right answer. This change would add quite a bit of public surface.

2021-05-27 03:01 UTC, shinfan commented
Thanks for review. PTAL. @codyoss 

Not related to this PR but I am a little concerned about the package name as I feel we should have the top-level package called "mtls" instead of "cert" to be more future proof, since we will add some more mtls related features later. Is this something too late to change?

2021-06-01 17:21 UTC, codyoss commented
What is the use case where these methods need to be exposed? We already allow for returning a `http.Client` that uses the certSource to setup the TLSConfig. I guess I am lacking the proper context here, is there a design doc that can be shared with me? Are other languages exposing similar features?

2021-06-09 16:10 UTC, codyoss commented
Closing this PR for now as we decided to take a different direction.

2021-06-09 16:10 UTC, closed without merging