feat(idtoken): NewTokenSource allows impersonated_service_account creds
googleapis/google-api-go-client pull request #1792
Opened 2022-12-27 21:54 UTC by adrianajg

- Allow NewTokenSource function to accept authorization credentials of type `impersonated_service_account`
- Write unit test for NewTokenSource function
    - To test functionality, run the following command on local machine before executing test:
    ```sh
    $ gcloud auth application-default login --impersonate-service-account=<service_account_email_address>
    ```

Fixes: #873 (impersonated_service_account only, not authorized_user)

2022-12-28 15:57 UTC, codyoss requested changes

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken.go
> +	option.WithScopes()
nit: this looks unintentional.

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken.go
> +// isOfAllowedType returns the credentials type as a string, and an error.
nit: update docs to reflect new name

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken.go
> +func getAllowedType(data []byte) (string, error) {
I wonder if instead this should return an enum(Go does not have such a thing but their are patterns). I think that would clean up this code a bit.

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken.go
> +		return "", fmt.Errorf("idtoken: credential must be service_account or impersonated_service_account, found %q", f.Type)
More types may be added over time, be less specific and maybe just say it is an unsupported type.

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken.go
> +func getAllowedType(data []byte) (string, error) {
If we did an enum I think this should not return an error, and then in the calling code handle the undefined enum state.

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken.go
> +	if allowedType == "service_account" {
Feels like this should we a switch instead of an if/else

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken_test.go
> +// Copyright 2020 Google LLC.
nit: update year

2022-12-28 15:57 UTC, codyoss commented on idtoken/idtoken_test.go
> +package idtoken
I think this test should either be removed for now or else we need to turn it into a real integration test and setup creds. As is this is causing CI to fail.

2022-12-28 16:34 UTC, adrianajg commented on idtoken/idtoken.go
> +	option.WithScopes()
Removed.

2023-01-03 17:52 UTC, codyoss commented
@adrianajg It appears you have files that are not properly formatted

2023-01-03 17:54 UTC, codyoss commented on idtoken/integration_test.go
> +func TestNewTokenSource_WithImpersonatedServiceAccountCreds(t *testing.T) {
Let remove this for now.

2023-01-03 22:40 UTC, JohnsoNeal2013 commented on idtoken/integration_test.go
> +func TestNewTokenSource_WithImpersonatedServiceAccountCreds(t *testing.T) {
Yea

2023-01-03 22:41 UTC, JohnsoNeal2013 commented
Can someone please help me

2023-01-04 14:53 UTC, adrianajg reviewed
Addressed changes, let me know if you see anything else. Thanks!

2023-01-04 15:35 UTC, codyoss approved these changes

2023-01-04 15:47 UTC, merged