draft(gensupport): merge x-goog-api-client vals into a single header
googleapis/google-api-go-client pull request #2612
Opened 2024-05-29 22:58 UTC by BrennaEpp

2024-06-05 19:22 UTC, quartzmo requested changes
Can you expand `TestSendRequestHeader` (or add a new test) to cover this change?

2024-06-07 03:50 UTC, tritone approved these changes
Overall looks good; thanks for adding the test.

2024-06-07 03:50 UTC, tritone commented on internal/gensupport/send.go
> +				for _, v := range vals {
nit: could you flip this conditional? Seems more readable to have the default case as the "else".

2024-06-07 17:13 UTC, quartzmo approved these changes

2024-06-07 18:29 UTC, shollyman approved these changes

2024-06-10 19:38 UTC, tritone approved these changes

2024-06-10 20:50 UTC, merged